In [1]:
# For numerical calculations
import numpy as np
import pandas as pd
import scipy as sp
import math
import matplotlib.animation as animation
from scipy.integrate import odeint
from numpy import arange
from pylab import *
from scipy.integrate import odeint
import scipy.optimize 
from scipy.optimize import leastsq
from math import exp
from collections import OrderedDict
from sklearn.linear_model import LinearRegression
pd.options.mode.chained_assignment = None
import git

# Import plotting features
import matplotlib.pyplot as plt
import seaborn as sns

# Find home directory for repo
repo = git.Repo("./", search_parent_directories=True)
homedir = repo.working_dir

# Set plot style
sns.set_style("ticks")
sns.set_palette("colorblind", color_codes=True)
sns.set_context("paper")

# Magic command to plot inline
%matplotlib inline

#To graph in SVG (high def)
%config InlineBackend.figure_format="svg"

In [2]:
# Import table with data
df_data =  pd.read_csv ('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210330_EA.csv')

# Keep only rows with Peak Nr=3, since Peak Nr=1,2,4 and 5 
# correspond to the reference gas
#Select rows to drop
i1 = df_data[df_data['Peak_Nr'] == 1].index
i2 = df_data[df_data['Peak_Nr'] == 2].index
i4 = df_data[df_data['Peak_Nr'] == 4].index
i5 = df_data[df_data['Peak_Nr'] == 5].index
#Drop rows in place
df_data.drop(i1, inplace=True)
df_data.drop(i2, inplace=True)
df_data.drop(i4, inplace=True)
df_data.drop(i5, inplace=True)
df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330

Then, let's load the data for the blanks:

In [3]:
# Import table with the raw data for blanks
df_blanks = pd.read_csv('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210330_blanks.csv')

# Remove rows with missing data
df_blanks.dropna(how='any', inplace=True)

# Keep only rows with Peak Nr=3
#Select rows to drop
i1 = df_blanks[df_blanks['Peak_Nr'] == 1].index
i2 = df_blanks[df_blanks['Peak_Nr'] == 2].index
i4 = df_blanks[df_blanks['Peak_Nr'] == 4].index
i5 = df_blanks[df_blanks['Peak_Nr'] == 5].index
#Drop rows in place
df_blanks.drop(i1, inplace=True)
df_blanks.drop(i2, inplace=True)
df_blanks.drop(i4, inplace=True)
df_blanks.drop(i5, inplace=True)
df_blanks.head()

,Identifier,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Date
2,blank,3,1.655,1.579,0.076,47,224,8.189,20210330
7,blank,3,3.287,3.136,0.150,96,457,4.588,20210330
12,blank,3,1.619,1.545,0.074,49,234,3.305,20210330
17,blank,3,2.212,2.111,0.101,66,315,9.318,20210330
22,blank,3,1.941,1.852,0.089,60,285,5.494,20210330

Finally, let's load the data for the linearity test at the beginning of the run:

In [4]:
# Import file
df_lin =  pd.read_csv('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210330_linearity.csv')
df_lin.head()

  Identifier  Peak_Nr  Ampl_64  Ampl_66   d34S
0  linearity        1      645     3077 -0.196
1  linearity        2     1793     8554  0.000
2  linearity        3     2476    11813  0.145
3  linearity        4     3345    15961  0.471
4  linearity        5     4064    19396  0.722

Now, let's implement the corrections.

## Blank correction

In [5]:
# Get the average area all for the blanks
blank_area_all_average = df_blanks["Area_All"].mean()

# Get the average d34S for the blanks
blank_d34s_average = df_blanks["d34S"].mean()

# Append a column to the data dataframe with the 
# correction of area by blank: substraction of the
# area of the measurement by the area of the blank

df_data['Correction_of_area_blank'] = \
    np.subtract(df_data['Area_All'], blank_area_all_average)

# Correction of d34S by blank: 
    
# Get the product of the d34S by the area of each measurement
num1 = np.multiply (df_data['d34S'], df_data['Area_All'])
# Get the product of the d34S by the area of the average of the blanks
num2 = blank_d34s_average * blank_area_all_average  
#Subtract the product of d34S by the product of the blanks
num = np.subtract (num1, num2)
#Divide by the area corrected by blank and
#append column to the data dataframe
df_data['Correction_of_d34S_blank'] = \
    np.divide (num, df_data['Correction_of_area_blank'])

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330,39.612769,-3.169031
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330,41.876769,24.629440
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330,56.905769,25.048029

## Linearity correction

In [6]:
# Create variables for linear regression
# x will be the amplitude of the peak of mass 64 = ^32S + ^16O + ^16O
# We divided by 1000 to convert volts ot milivolts
x = (df_lin['Ampl_64'].values/1000).reshape((-1,1))
# y will be the values of d34S
y = (df_lin['d34S'])

# Create model of linear regression
model = LinearRegression().fit(x,y)

#Determine R square, intercept and slope
r_sq = model.score(x,y)
intercept = model.intercept_
s = model.coef_
slope=s[0]

# Calculate an amplitude difference by centering around an arbitrary 
# value in the Ampl_64 column of the data dataframe  
num= np.subtract(df_data['Ampl_64'], 1100)
ampl_difference = np.divide (num, 1000)

# Calculate the amplitude correction factor
ampl_correction_factor = (slope * ampl_difference)+intercept

# Correct the d34S corrected by amplitude by
# subtracting the blank corrected data by the amplitude correction
# factor and append the column to the data dataframe
df_data['Correction_of_d34S_by_amplitude'] = \
    np.subtract(df_data['Correction_of_d34S_blank'], ampl_correction_factor)

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330,39.612769,-3.169031,-2.796926
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938,1.486106
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201,0.971728
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330,41.876769,24.629440,24.990274
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330,56.905769,25.048029,25.303852

## Standard correction

First, let's create a category column in the dataframe according to the size of the area of the peak of each sample and standard.

In [7]:
# Correct each sample by standards with similar areas

#Create standard correction group empty list
Std_group = []
# Classify the area of the samples by category 
# Loop through dataframe rows
for row in df_data['Area_All']:
    if row <= 45:
        Std_group.append ('low')
    elif row >= 45.1:
        Std_group.append ('high')        
# Append to data dataframe 
df_data['Std_group'] = Std_group
df_data.head()

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330,39.612769,-3.169031,-2.796926,low
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938,1.486106,low
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201,0.971728,high
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330,41.876769,24.629440,24.990274,low
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330,56.905769,25.048029,25.303852,high

In [8]:
# Create df with only standard data
df_standards = df_data[(df_data.Type == 'standard')] 
#Sort values by ID and area
df_standards = df_standards.sort_values(['Identifier', 'Date', 'Area_All'])

df_standards

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938,1.486106,low
47,AGS2,NaN,NaN,3,37.162,35.469,1.693,1259,5996,1.373,standard,20210330,34.947769,1.091041,1.493369,low
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201,0.971728,high
52,AGS2,NaN,NaN,3,46.408,44.293,2.114,1424,6784,1.252,standard,20210330,44.193769,1.022969,1.383035,high
32,AGS2,NaN,NaN,3,48.930,46.701,2.229,1468,6990,1.253,standard,20210330,46.715769,1.036381,1.385177,high
27,AGS2,NaN,NaN,3,64.870,61.915,2.955,1967,9367,1.412,standard,20210330,62.655769,1.256109,1.477098,high
112,AGS2,NaN,NaN,3,18.546,17.698,0.848,599,2865,1.706,standard,20210331,16.331769,1.147794,1.719165,low
252,AGS2,NaN,NaN,3,22.572,21.537,1.034,737,3532,1.377,standard,20210331,20.357769,0.893402,1.429428,low
182,AGS2,NaN,NaN,3,32.125,30.654,1.471,1029,4929,1.158,standard,20210331,29.910769,0.812643,1.273880,low
322,AGS2,NaN,NaN,3,48.816,46.585,2.231,1533,7324,1.170,standard,20210331,46.601769,0.948907,1.281055,high
107,AGS2,NaN,NaN,3,52.458,50.060,2.398,1807,8638,0.703,standard,20210331,50.243769,0.477353,0.739322,high
257,AGS2,NaN,NaN,3,57.565,54.926,2.639,2017,9671,0.918,standard,20210331,55.350769,0.721773,0.929956,high
187,AGS2,NaN,NaN,3,62.289,59.436,2.853,1941,9295,0.950,standard,20210331,60.074769,0.770383,0.998031,high
327,AGS2,NaN,NaN,3,64.813,61.859,2.954,2143,10216,1.366,standard,20210331,62.598769,1.208340,1.384250,high
42,AGS26,NaN,NaN,3,33.358,31.805,1.553,1055,5142,23.112,standard,20210330,31.143769,24.341181,24.795758,low
57,AGS26,NaN,NaN,3,41.151,39.239,1.912,1272,6184,23.903,standard,20210330,38.936769,24.931149,25.330146,low
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330,41.876769,24.629440,24.990274,low
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330,56.905769,25.048029,25.303852,high
37,AGS26,NaN,NaN,3,60.590,57.767,2.822,1926,9394,24.184,standard,20210330,58.375769,24.880436,25.111926,high
62,AGS26,NaN,NaN,3,70.841,67.547,3.294,2072,10090,24.461,standard,20210330,68.626769,25.062344,25.256440,high
262,AGS26,NaN,NaN,3,22.986,21.919,1.066,764,3708,22.344,standard,20210331,20.771769,24.105082,24.634193,low
122,AGS26,NaN,NaN,3,30.777,29.340,1.437,989,4834,23.302,standard,20210331,28.562769,24.656982,25.128464,low
332,AGS26,NaN,NaN,3,32.238,30.737,1.502,1033,5038,22.920,standard,20210331,30.023769,24.180874,24.641087,low
117,AGS26,NaN,NaN,3,38.471,36.675,1.797,1303,6370,23.449,standard,20210331,36.256769,24.525420,24.916478,low
197,AGS26,NaN,NaN,3,41.158,39.236,1.922,1327,6491,23.582,standard,20210331,38.943769,24.591713,24.976623,low
267,AGS26,NaN,NaN,3,44.083,42.029,2.054,1391,6785,23.644,standard,20210331,41.868769,24.586452,24.954970,low
192,AGS26,NaN,NaN,3,44.109,42.049,2.060,1399,6840,23.468,standard,20210331,41.894769,24.400565,24.767035,low
337,AGS26,NaN,NaN,3,60.718,57.887,2.830,1847,9014,23.947,standard,20210331,58.503769,24.632942,24.884667,high

In [9]:
#Drop outliers in place
#df_standards.drop(df_standards.index[10], inplace=True)
#df_standards.drop(df_standards.index[0], inplace=True)

# Calculate the slope and intercept for calculated vs. true value of the stds

# Append true value column to the standard table
# For AGS2
df_standards.loc[df_standards['Identifier'] \
                  == 'AGS2', 'True_d34S'] = 1.89
# For AGS26
df_standards.loc[df_standards['Identifier'] \
                  == 'AGS26', 'True_d34S'] = 26.83
                       
# Group by Std_group
df_stdgroup = df_standards.groupby (['Std_group'])

df_standards.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,True_d34S
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938,1.486106,low,1.89
47,AGS2,NaN,NaN,3,37.162,35.469,1.693,1259,5996,1.373,standard,20210330,34.947769,1.091041,1.493369,low,1.89
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201,0.971728,high,1.89
52,AGS2,NaN,NaN,3,46.408,44.293,2.114,1424,6784,1.252,standard,20210330,44.193769,1.022969,1.383035,high,1.89
32,AGS2,NaN,NaN,3,48.930,46.701,2.229,1468,6990,1.253,standard,20210330,46.715769,1.036381,1.385177,high,1.89

Below, we make a linear regression for the standards of each area group.

In [10]:
# Get the slope and intercept for the standards of each group
# Define column names
names = ['Std_group', 'R squared', 'Intercept', 'Slope']

# Initialize empty dataframe to save fit results
df_linreg_stds = pd.DataFrame(columns=names)
                 
# Create variables for linear regression
#Loop through standard groups                       
for group, data in enumerate (df_stdgroup):
    #x will be the values of d34S of the stds corrected by blanks and linearity
    x_std = data[1].Correction_of_d34S_by_amplitude.values.reshape((-1,1))
    #y will be the true values of d34S of each standard
    y_std = data[1].True_d34S
    # Create model
    model = LinearRegression().fit(x_std,y_std)
    #Determine R square, intercept and slope
    r_sq_stds = model.score(x_std,y_std)
    intercept_stds = model.intercept_
    s1 = model.coef_
    slope_stds = s1[0]
    # Store parameters and group as list
    params = (data[1].Std_group.unique(), r_sq_stds, intercept_stds, slope_stds)
 
    # Convert list to pandas Series
    series = pd.Series(params, index=names)   
    # Append parameters to dataframe
    df_linreg_stds = df_linreg_stds.append(series, ignore_index=True)
#Round the values of the dataframe to two decimal places
df_linreg_stds = df_linreg_stds.round(2)     
df_linreg_stds

  Std_group  R squared  Intercept  Slope
0    [high]        1.0       0.67   1.04
1     [low]        1.0       0.32   1.06

Finally, let's apply the standard correction to the samples based on their area:

In [11]:
#Apply corrections by true value and area

# Initialize lists to save values
slopes = []
intercepts = []
Correction_of_d34S_by_true_value = []

#loop through rows in dataframe
for index, row in df_data.iterrows():
    # Extract standard group
    Std_group = row.Std_group
    # Extract slope and intercept
    slope = df_linreg_stds[df_linreg_stds.Std_group == Std_group].Slope.iloc[0]
    intercept = df_linreg_stds[df_linreg_stds.Std_group == Std_group].Intercept.iloc[0]
    slopes.append(slope)
    intercepts.append(intercept)
    # Compute corrected concentration
    Correction_of_d34S_by_true_value.append(intercept + slope * row.Correction_of_d34S_by_amplitude)
    
# Append values to dataframe
df_data['Correction_of_d34S_by_true_value'] = Correction_of_d34S_by_true_value

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,Correction_of_d34S_by_true_value
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330,39.612769,-3.169031,-2.796926,low,-2.644742
7,AGS2,NaN,NaN,3,28.331,27.041,1.290,877,4178,1.364,standard,20210330,26.116769,0.985938,1.486106,low,1.895272
12,AGS2,NaN,NaN,3,46.367,44.256,2.111,1512,7198,0.882,standard,20210330,44.152769,0.634201,0.971728,high,1.680597
17,AGS26,NaN,NaN,3,44.091,42.044,2.047,1421,6907,23.685,standard,20210330,41.876769,24.629440,24.990274,low,26.809691
22,AGS26,NaN,NaN,3,59.120,56.367,2.753,1831,8927,24.328,standard,20210330,56.905769,25.048029,25.303852,high,26.986006

Since all the corrections have been done, we will now export the corrected data, which must be combined with the quantification data to get the plots of sulfide degradation and change in the $\delta^{34}S$ of the remaining sulfide as a function of time or -ln of sulfide remaining.

In [12]:
# Create dataframe that includes only data from the samples
df_samples = df_data[(df_data.Type == 'sample')]

# Export data table
df_samples.to_csv('/Users/daniosro/git/MSO/ctep_wt/data/processed/EA/20210330_EA.csv')
df_samples.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Date,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,Correction_of_d34S_by_true_value
2,d,0.0,1.0,3,41.827,39.925,1.903,1377,6547,-2.693,sample,20210330,39.612769,-3.169031,-2.796926,low,-2.644742
67,d,35.0,1.0,3,27.697,26.438,1.259,859,4078,-6.583,sample,20210331,25.482769,-7.660993,-7.156215,low,-7.265588
72,d,35.0,3.0,3,27.718,26.457,1.261,882,4191,-6.852,sample,20210331,25.503769,-7.952460,-7.453573,low,-7.580787
77,b_march22,17.5,7.0,3,26.705,25.487,1.217,843,4014,-4.677,sample,20210331,24.490769,-5.626335,-5.117458,low,-5.104505
82,b_march22,17.5,8.0,3,28.676,27.367,1.308,917,4376,-4.476,sample,20210331,26.461769,-5.337805,-4.847881,low,-4.818754

### Analytical repeatability of measurements

Let's calculate the analytical repeatability of the EA-IRMS measurements.

In [13]:
# Update standard df
# Create a dataframe for only standards from the updated data dataframe
df_standards = df_data[(df_data.Type == 'standard')]
#Sort values
df_standards = df_standards.sort_values(['Identifier', 'Area_All'])

#Group standards by identifier and area
grouped_standards = df_standards.groupby(['Identifier', 'Std_group'])

# Determine the mean of each standard  and rename the series
mean_stds = grouped_standards['Correction_of_d34S_by_true_value'].mean()
mean_stds = mean_stds.rename("d34S_mean")

# Determine the standard deviation of each standard  and rename the series
std_dev_stds = grouped_standards['Correction_of_d34S_by_true_value'].std()
std_dev_stds = std_dev_stds.rename("d34S_stdev")

#Pass series to individual dataframes
df_mean_stds=mean_stds.to_frame()
df_std_dev_stds=std_dev_stds.to_frame()

In [14]:
#merge the mean and standard deviation dataframes
df_anrep = pd.merge(df_mean_stds, df_std_dev_stds,  how='outer', on=['Identifier', 'Std_group'])

#Reset index of the dataframe
df_anrep = df_anrep.reset_index()

#Add column of true value of the standards
df_anrep.loc[df_anrep['Identifier'] \
                  == 'AGS2', 'True_d34S'] = 1.89
df_anrep.loc[df_anrep['Identifier'] \
                  == 'AGS26', 'True_d34S'] = 26.83

#Determine the accuracy by subtracting the true value from the average value of each standard
df_anrep ['Accuracy'] = abs(df_anrep ['True_d34S'] - df_anrep ['d34S_mean'])
df_anrep

  Identifier Std_group  d34S_mean  d34S_stdev  True_d34S  Accuracy
0       AGS2      high   1.889071    0.274217       1.89  0.000929
1       AGS2       low   1.889213    0.169648       1.89  0.000787
2      AGS26      high  26.814790    0.195847      26.83  0.015210
3      AGS26       low  26.728313    0.228699      26.83  0.101687

## Import the quantification data and calculate the fraction of sulfide remaining

Let's begin by loading the sulfide quantification data (Cline assay):

In [15]:
# Import table with data
df_cline =  pd.read_csv(f'{homedir}/ctep_wt/data/raw/cline_assay/20210322_cline.csv') 
#See data
df_cline.head()

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group
0,0.567,standard,2.5,NaN,1.0,1.0,NaN,d
1,0.747,standard,2.5,NaN,2.0,1.0,NaN,d
2,0.857,standard,2.5,NaN,3.0,1.0,NaN,d
3,0.561,standard,1.7,NaN,1.0,1.0,NaN,d
4,0.625,standard,1.7,NaN,2.0,1.0,NaN,d

In [16]:
#Filter by standard group
df_cline_b = df_cline[(df_cline.stdcurve_group == 'b')]
#Filter by blank only
df_blank_b = df_cline_b[(df_cline_b.hyp_conc == 0)]
#Get the average of the absorbance for the blanks
avg_blank_b = df_blank_b['absorbance'].mean()

#Filter by second standard group
df_cline_d = df_cline[(df_cline.stdcurve_group == 'd')]
#Filter by blank only
#df_blank_d = df_cline_d[(df_cline_d.hyp_conc == 0)]
#Get the average of the absorbance for the blanks
avg_blank_d = df_blank_b['absorbance'].mean()

#Filter by third standard group
df_cline_c = df_cline[(df_cline.stdcurve_group == 'c')]
#Filter by blank only
df_blank_c = df_cline_c[(df_cline_c.hyp_conc == 0)]
#Get the average of the absorbance for the blanks
avg_blank_c = df_blank_c['absorbance'].mean()

#Subtract average of the blank absorbance from all the absorbances
#Create empty list to append the corrected absorbances
abs_corr = []
#Loop through rows in the dataframe with all the data
for i, row in df_cline.iterrows():
    #Determine corrected absorbance for the first standard group
    if row.stdcurve_group == 'd':
        absorbance = row.absorbance - avg_blank_d
    #Determine corrected absorbance for the second standard group
    elif row.stdcurve_group == 'b':
        absorbance = row.absorbance - avg_blank_b
    #Determine corrected absorbance for the third standard group
    else:
        absorbance = row.absorbance - avg_blank_c
    #Append corrected absorbance to list
    abs_corr.append (absorbance)
        
# Create a column from the list
df_cline['abs_corr'] = abs_corr
df_cline

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group,abs_corr
0,0.567,standard,2.5,NaN,1.0,1.0,NaN,d,0.535
1,0.747,standard,2.5,NaN,2.0,1.0,NaN,d,0.715
2,0.857,standard,2.5,NaN,3.0,1.0,NaN,d,0.825
3,0.561,standard,1.7,NaN,1.0,1.0,NaN,d,0.529
4,0.625,standard,1.7,NaN,2.0,1.0,NaN,d,0.593
...,...,...,...,...,...,...,...,...,...
190,1.153,sample,NaN,c,2.0,1.0,0.0,c,1.119
191,1.076,sample,NaN,c,3.0,1.0,0.0,c,1.042
192,1.175,sample,NaN,d,1.0,1.0,0.0,d,1.143
193,1.006,sample,NaN,d,2.0,1.0,0.0,d,0.974
194,1.066,sample,NaN,d,3.0,1.0,0.0,d,1.034

In [17]:
#Make standard curve

#Filter by standard group
df_cline_d = df_cline[(df_cline.stdcurve_group == 'd')]
df_cline_b = df_cline[(df_cline.stdcurve_group == 'b')]
df_cline_c = df_cline[(df_cline.stdcurve_group == 'c')]

#Filter by standard only for the first standard group
df_standard_d = df_cline_d[(df_cline_d.type == 'standard')]
#Filter by standard only for the second standard group
df_standard_b = df_cline_b[(df_cline_b.type == 'standard')]
#Filter by standard only for the third standard group
df_standard_c = df_cline_c[(df_cline_c.type == 'standard')]

# Calculate linear regression for the first standard group
z_b = np.polyfit(df_standard_b.abs_corr, df_standard_b.hyp_conc, 1)
p_b = np.poly1d(z_b)
# Calculate linear regression for the second standard group
z_d = np.polyfit(df_standard_d.abs_corr, df_standard_d.hyp_conc, 1)
p_d = np.poly1d(z_d)
# Calculate linear regression for the third standard group
z_c = np.polyfit(df_standard_c.abs_corr, df_standard_c.hyp_conc, 1)
p_c = np.poly1d(z_c)

#Insert into a new column in the standard dataframe for the first standard group
df_standard_b.insert(4,'reg',p_b(df_standard_b['abs_corr']))
df_standard_b.head()

,absorbance,type,hyp_conc,treatment,reg,well,replicate,time_h,stdcurve_group,abs_corr
171,0.806,standard,2.5,NaN,2.326618,1.0,1.0,NaN,b,0.774
172,0.841,standard,2.5,NaN,2.435103,2.0,1.0,NaN,b,0.809
173,0.831,standard,2.5,NaN,2.404108,3.0,1.0,NaN,b,0.799
174,0.394,standard,1.0,NaN,1.049594,1.0,1.0,NaN,b,0.362
175,0.420,standard,1.0,NaN,1.130183,2.0,1.0,NaN,b,0.388

In [18]:
#Insert into a new column in the standard dataframe for the second standard group
df_standard_d.insert(4,'reg',p_d(df_standard_d['abs_corr']))
df_standard_d.head()

,absorbance,type,hyp_conc,treatment,reg,well,replicate,time_h,stdcurve_group,abs_corr
0,0.567,standard,2.5,NaN,1.750685,1.0,1.0,NaN,d,0.535
1,0.747,standard,2.5,NaN,2.338411,2.0,1.0,NaN,d,0.715
2,0.857,standard,2.5,NaN,2.697576,3.0,1.0,NaN,d,0.825
3,0.561,standard,1.7,NaN,1.731094,1.0,1.0,NaN,d,0.529
4,0.625,standard,1.7,NaN,1.940063,2.0,1.0,NaN,d,0.593

In [19]:
#Insert into a new column in the standard dataframe for the third standard group
df_standard_c.insert(4,'reg',p_c(df_standard_c['abs_corr']))
df_standard_c.head()

,absorbance,type,hyp_conc,treatment,reg,well,replicate,time_h,stdcurve_group,abs_corr
105,1.041,standard,2.08,NaN,2.076804,NaN,NaN,NaN,c,1.007
106,1.004,standard,2.08,NaN,2.002847,NaN,NaN,NaN,c,0.970
107,0.867,standard,2.08,NaN,1.729008,NaN,NaN,NaN,c,0.833
108,0.713,standard,1.38,NaN,1.421188,NaN,NaN,NaN,c,0.679
109,0.678,standard,1.38,NaN,1.351229,NaN,NaN,NaN,c,0.644

In [20]:
#Plot the regression line for the standard from the first standard group
ax = df_standard_b.plot.scatter(x = 'abs_corr',y='hyp_conc')
df_standard_b.plot(x = 'abs_corr',y='reg',c='r',ax=ax)
ax.set_xlabel('Corrected absorbance')
ax.set_ylabel('Concentration ($mM$)')

'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.

Text(0, 0.5, 'Concentration ($mM$)')

In [21]:
# Calculate the concentration of each sample

# Create empty list to append concentrations
conc = []
#Loop through full dataframe
for i, row in df_cline.iterrows():
    #Apply the linear regression for the first standard group samples based on the standard curve for that plate
    if row.stdcurve_group == 'b':
        real_conc = row.abs_corr *z_b[0] + z_b[1]
     #Apply the linear regression for the second standard group samples based on the standard curve for that plate
    elif row.stdcurve_group == 'd':
        real_conc = row.abs_corr *z_d[0] + z_d[1]
    #Apply the linear regression for the third standard group samples based on the standard curve for that plate
    else:
        real_conc = row.abs_corr *z_c[0] + z_c[1]
    #Append calculated concentrations to list
    conc.append (real_conc)
        
# Create a column from the list
df_cline['concentration'] = conc
df_cline.head()

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group,abs_corr,concentration
0,0.567,standard,2.5,NaN,1.0,1.0,NaN,d,0.535,1.750685
1,0.747,standard,2.5,NaN,2.0,1.0,NaN,d,0.715,2.338411
2,0.857,standard,2.5,NaN,3.0,1.0,NaN,d,0.825,2.697576
3,0.561,standard,1.7,NaN,1.0,1.0,NaN,d,0.529,1.731094
4,0.625,standard,1.7,NaN,2.0,1.0,NaN,d,0.593,1.940063

In [22]:
# Filter by sample only
df_samples_cline = df_cline[(df_cline.type == 'sample')]
df_samples_cline.head()

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group,abs_corr,concentration
21,0.451,sample,NaN,d,1.0,1.0,18.25,d,0.419,1.371928
22,0.478,sample,NaN,d,2.0,1.0,18.25,d,0.446,1.460087
23,0.448,sample,NaN,d,3.0,1.0,18.25,d,0.416,1.362133
24,0.471,sample,NaN,d,1.0,2.0,18.25,d,0.439,1.437231
25,0.489,sample,NaN,d,2.0,2.0,18.25,d,0.457,1.496004

In [23]:
#Get average concentrations of the three wells for each replicate
df_samples_cline['avg_conc'] = df_samples_cline.groupby(['replicate','time_h'])['concentration'].transform(mean)
df_samples_cline.head()

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group,abs_corr,concentration,avg_conc
21,0.451,sample,NaN,d,1.0,1.0,18.25,d,0.419,1.371928,1.398049
22,0.478,sample,NaN,d,2.0,1.0,18.25,d,0.446,1.460087,1.398049
23,0.448,sample,NaN,d,3.0,1.0,18.25,d,0.416,1.362133,1.398049
24,0.471,sample,NaN,d,1.0,2.0,18.25,d,0.439,1.437231,1.449203
25,0.489,sample,NaN,d,2.0,2.0,18.25,d,0.457,1.496004,1.449203

We will calculate the fraction of reactant remaining for each replicate at each time point:

In [24]:
#Create ID column with the combination of treatment, time and replicate
df_samples_cline['ID'] = df_samples_cline['treatment'] + '_' +\
df_samples_cline['time_h'].astype(int).map(str) + '_' + \
df_samples_cline['replicate'].map(str)

# Create new treat_rep column with the combination of treatment and replicate
#df_samples_cline['treat_rep'] = df_samples_cline['treatment'] + '_' +\
#df_samples_cline['replicate'].map(str)

# Get the max values for average concentration for each treatment and replicate and 
# append it to a new column
df_samples_cline['max_conc'] = \
df_samples_cline.groupby(['treatment'])['avg_conc'].transform(max)

# Get the fraction of reactant remaining for each time point
df_samples_cline['f_R'] = abs(np.divide(df_samples_cline['avg_conc'], \
               df_samples_cline['max_conc']))

# Remove duplicates
df_samples_cline = df_samples_cline.drop_duplicates(subset ="ID")

df_samples_cline

,absorbance,type,hyp_conc,treatment,well,replicate,time_h,stdcurve_group,abs_corr,concentration,avg_conc,ID,max_conc,f_R
21,0.451,sample,NaN,d,1.0,1.0,18.25,d,0.419,1.371928,1.398049,d_18_1.0,2.841679,0.491980
24,0.471,sample,NaN,d,1.0,2.0,18.25,d,0.439,1.437231,1.449203,d_18_2.0,2.841679,0.509981
27,0.422,sample,NaN,d,1.0,3.0,18.25,d,0.390,1.277239,1.317509,d_18_3.0,2.841679,0.463638
30,0.257,sample,NaN,d,1.0,1.0,25.50,d,0.225,0.738491,0.802705,d_25_1.0,2.841679,0.282476
33,0.269,sample,NaN,d,1.0,2.0,25.50,d,0.237,0.777672,0.779849,d_25_2.0,2.841679,0.274433
36,0.388,sample,NaN,d,1.0,3.0,25.50,d,0.356,1.166224,1.161871,d_25_3.0,2.841679,0.408868
39,0.215,sample,NaN,d,1.0,1.0,31.50,d,0.183,0.601355,0.580675,d_31_1.0,2.841679,0.204342
42,0.232,sample,NaN,d,1.0,2.0,31.50,d,0.200,0.656862,0.689513,d_31_2.0,2.841679,0.242643
45,0.310,sample,NaN,d,1.0,3.0,31.50,d,0.278,0.911543,0.885422,d_31_3.0,2.841679,0.311584
48,0.126,sample,NaN,d,1.0,1.0,40.50,d,0.094,0.310757,0.293343,d_40_1.0,2.841679,0.103229
51,0.127,sample,NaN,d,1.0,2.0,40.50,d,0.095,0.314022,0.345585,d_40_2.0,2.841679,0.121613
54,0.234,sample,NaN,d,1.0,3.0,40.50,d,0.202,0.663392,0.600266,d_40_3.0,2.841679,0.211236
57,0.084,sample,NaN,d,1.0,3.0,51.50,d,0.052,0.173621,0.175798,d_51_3.0,2.841679,0.061864
60,0.742,sample,NaN,b_march22,1.0,7.0,0.00,b,0.710,2.128246,2.122046,b_march22_0_7.0,2.122046,1.000000
63,0.071,sample,NaN,d,1.0,1.0,35.00,d,0.039,0.131174,0.144235,d_35_1.0,2.841679,0.050757
66,0.113,sample,NaN,d,1.0,2.0,35.00,d,0.081,0.268310,0.272664,d_35_2.0,2.841679,0.095952
69,0.098,sample,NaN,d,1.0,3.0,35.00,d,0.066,0.219333,0.192123,d_35_3.0,2.841679,0.067609
72,0.301,sample,NaN,b_march22,1.0,7.0,17.50,b,0.269,0.761334,0.767533,b_march22_17_7.0,2.122046,0.361695
75,0.290,sample,NaN,b_march22,1.0,8.0,17.50,b,0.258,0.727239,0.738604,b_march22_17_8.0,2.122046,0.348062
78,0.212,sample,NaN,b_march22,1.0,9.0,17.50,b,0.180,0.485472,0.590857,b_march22_17_9.0,2.122046,0.278438
81,0.164,sample,NaN,b_march22,1.0,7.0,21.25,b,0.132,0.336692,0.317062,b_march22_21_7.0,2.122046,0.149413
84,0.149,sample,NaN,b_march22,1.0,8.0,21.25,b,0.117,0.290199,0.265402,b_march22_21_8.0,2.122046,0.125069
87,0.104,sample,NaN,b_march22,1.0,9.0,21.25,b,0.072,0.150718,0.166216,b_march22_21_9.0,2.122046,0.078328
90,0.112,sample,NaN,b_march22,1.0,7.0,22.75,b,0.080,0.175515,0.206510,b_march22_22_7.0,2.122046,0.097317
93,0.102,sample,NaN,b_march22,1.0,8.0,22.75,b,0.070,0.144519,0.145552,b_march22_22_8.0,2.122046,0.068590
96,0.075,sample,NaN,b_march22,1.0,9.0,22.75,b,0.043,0.060830,0.052565,b_march22_22_9.0,2.122046,0.024771
99,0.091,sample,NaN,b_march22,1.0,7.0,24.00,b,0.059,0.110424,0.108357,b_march22_24_7.0,2.122046,0.051063
102,0.075,sample,NaN,b_march22,1.0,8.0,24.00,b,0.043,0.060830,0.047399,b_march22_24_8.0,2.122046,0.022336
135,0.760,sample,NaN,c,1.0,1.0,10.00,c,0.726,1.515133,1.471825,c_10_1.0,2.841679,0.517942
138,0.748,sample,NaN,c,1.0,2.0,10.00,c,0.714,1.491147,1.438512,c_10_2.0,2.841679,0.506219
141,0.755,sample,NaN,c,1.0,3.0,10.00,c,0.721,1.505139,1.554444,c_10_3.0,2.841679,0.547016
144,0.528,sample,NaN,c,1.0,1.0,22.00,c,0.494,1.051405,1.116700,c_22_1.0,2.841679,0.392972
147,0.525,sample,NaN,c,1.0,2.0,22.00,c,0.491,1.045409,1.159342,c_22_2.0,2.841679,0.407978
150,0.590,sample,NaN,c,1.0,3.0,22.00,c,0.556,1.175332,1.101376,c_22_3.0,2.841679,0.387579
153,0.399,sample,NaN,c,1.0,1.0,34.00,c,0.365,0.793556,0.805549,c_34_1.0,2.841679,0.283476
156,0.470,sample,NaN,c,1.0,2.0,34.00,c,0.436,0.935473,0.954795,c_34_2.0,2.841679,0.335997
159,0.518,sample,NaN,c,1.0,3.0,34.00,c,0.484,1.031417,1.015426,c_34_3.0,2.841679,0.357333
162,0.396,sample,NaN,c,1.0,1.0,103.50,c,0.362,0.787560,0.805549,c_103_1.0,2.841679,0.283476
165,0.455,sample,NaN,c,1.0,2.0,103.50,c,0.421,0.905491,0.837530,c_103_2.0,2.841679,0.294731
168,0.415,sample,NaN,c,1.0,3.0,103.50,c,0.381,0.825537,0.832866,c_103_3.0,2.841679,0.293090
189,1.154,sample,NaN,c,1.0,1.0,0.00,c,1.120,2.302672,2.841679,c_0_1.0,2.841679,1.000000
192,1.175,sample,NaN,d,1.0,1.0,0.00,d,1.143,3.735892,2.841679,d_0_1.0,2.841679,1.000000

In [25]:
# Export data table
df_samples_cline.to_csv(f'{homedir}/ctep_wt/data/processed/cline_assay/20210322_cline.csv')

## Create master table

Now, let's create a table to compile the corrected values from EA-IRMS and quantification of sulfide by Cline assay. We will begin by loading the processed EA data and dropping the non-needed columns:

In [26]:
# Import tables with the EA processed data
df_ea_1 = pd.read_csv(f'{homedir}/ctep_wt/data/processed/EA/20210330_EA.csv')

# Create empty master dataframe
df_master=pd.DataFrame()

# Fill master table
df_master['treatment'] = df_ea_1['Identifier']
df_master['d34S_corrected'] = df_ea_1['Correction_of_d34S_by_true_value']
df_master['replicate'] = df_ea_1['Replicate']
df_master['time_h'] = (df_ea_1['Time_h']).astype(int)

#Create new ID column with the combination of enzyme, time and date
df_master['ID'] = df_master['treatment'] + '_' +\
df_master['time_h'].map(str) + '_' + df_master['replicate'].map(str)

# Sort values
df_master = df_master.sort_values(['treatment', 'replicate', 'time_h'])
df_master.head()

    treatment  d34S_corrected  replicate  time_h                ID
40  b_march22       -2.644742        7.0       0   b_march22_0_7.0
3   b_march22       -5.104505        7.0      17  b_march22_17_7.0
6   b_march22       -5.425977        7.0      21  b_march22_21_7.0
9   b_march22       -6.457206        7.0      22  b_march22_22_7.0
12  b_march22       -7.476484        7.0      24  b_march22_24_7.0

Now, we will fuse this table with the quantification by Cline assay table:

In [27]:
# Append f_r (fraction of sulfide remaining) column to the master table               
df_master = df_master.merge(df_samples_cline.filter(['ID', 'f_R']), how='left',
                 left_on='ID', right_on='ID') 

# Append sulfide concentration column to the master table  
df_master = df_master.merge(df_samples_cline.filter(['ID', 'avg_conc']), \
                            how='left', left_on='ID', right_on='ID')  

# Append -ln(f_r) column to the master table
df_master['minus_ln_f_R'] = abs(-np.log(df_master['f_R']))

df_master.head()

,treatment,d34S_corrected,replicate,time_h,ID,f_R,avg_conc,minus_ln_f_R
0,b_march22,-2.644742,7.0,0,b_march22_0_7.0,1.000000,2.122046,0.000000
1,b_march22,-5.104505,7.0,17,b_march22_17_7.0,0.361695,0.767533,1.016955
2,b_march22,-5.425977,7.0,21,b_march22_21_7.0,0.149413,0.317062,1.901040
3,b_march22,-6.457206,7.0,22,b_march22_22_7.0,0.097317,0.206510,2.329786
4,b_march22,-7.476484,7.0,24,b_march22_24_7.0,0.051063,0.108357,2.974704

To determine the fractionation factor $^{34}\varepsilon$, we will use a linearized form of the Rayleigh distillation equation (Mariotti et al., 1981; Scott et al., 2014):

$$
ln (^{34}\delta_{S^{-2}} +1) = ln (^{34}\delta_{S^{-2},0} +1) + {^{34}\varepsilon} \cdot ln f,
$$ 

where $^{34}\delta_{S^{-2}}$ is the delta value for 34/32 S for sulfide at any given point, $^{34}\delta_{S^{-2},0}$ is the delta value for 34/32 S for sulfide at t = 0, ${^{34}\varepsilon}$ is the fractionation factor of 34/32 S in the sulfide oxidation reaction and f is the fraction of sulfide remaining at the point where $^{34}\delta_{S^{-2}}$ is measured. We will append a column corresponding to $ln (^{34}\delta_{S^{-2}} +1)$ to the dataframe.

In [28]:
#Calculate the ln (delta_sulfide+1) and append to dataframe
df_master['d34S_sulfide'] = 1000*np.log(df_master['d34S_corrected']/1000+1)

#Show dataframe
df_master

,treatment,d34S_corrected,replicate,time_h,ID,f_R,avg_conc,minus_ln_f_R,d34S_sulfide
0,b_march22,-2.644742,7.0,0,b_march22_0_7.0,1.000000,2.122046,0.000000,-2.648245
1,b_march22,-5.104505,7.0,17,b_march22_17_7.0,0.361695,0.767533,1.016955,-5.117578
2,b_march22,-5.425977,7.0,21,b_march22_21_7.0,0.149413,0.317062,1.901040,-5.440751
3,b_march22,-6.457206,7.0,22,b_march22_22_7.0,0.097317,0.206510,2.329786,-6.478144
4,b_march22,-7.476484,7.0,24,b_march22_24_7.0,0.051063,0.108357,2.974704,-7.504573
5,b_march22,-4.818754,8.0,17,b_march22_17_8.0,0.348062,0.738604,1.055375,-4.830402
6,b_march22,-5.625982,8.0,21,b_march22_21_8.0,0.125069,0.265402,2.078890,-5.641867
7,b_march22,-6.871147,8.0,22,b_march22_22_8.0,0.068590,0.145552,2.679603,-6.894862
8,b_march22,-8.885969,8.0,24,b_march22_24_8.0,0.022336,0.047399,3.801538,-8.925685
9,b_march22,-4.981191,9.0,17,b_march22_17_9.0,0.278438,0.590857,1.278562,-4.993638
10,b_march22,-6.104387,9.0,21,b_march22_21_9.0,0.078328,0.166216,2.546849,-6.123095
11,b_march22,-7.763392,9.0,22,b_march22_22_9.0,0.024771,0.052565,3.698089,-7.793684
12,c,-2.331153,1.0,0,c_0_1.0,1.000000,2.841679,0.000000,-2.333874
13,c,-2.223310,1.0,10,c_10_1.0,0.517942,1.471825,0.657892,-2.225786
14,c,-2.289056,1.0,22,c_22_1.0,0.392972,1.116700,0.934017,-2.291680
15,c,-2.022981,1.0,34,c_34_1.0,0.283476,0.805549,1.260626,-2.025030
16,c,-2.842720,1.0,103,c_103_1.0,0.283476,0.805549,1.260626,-2.846768
17,c,-2.023474,2.0,10,c_10_2.0,0.506219,1.438512,0.680786,-2.025524
18,c,-2.492137,2.0,22,c_22_2.0,0.407978,1.159342,0.896543,-2.495248
19,c,-2.824104,2.0,34,c_34_2.0,0.335997,0.954795,1.090654,-2.828099
20,c,-2.541596,2.0,103,c_103_2.0,0.294731,0.837530,1.221693,-2.544832
21,c,-2.465431,3.0,10,c_10_3.0,0.547016,1.554444,0.603277,-2.468476
22,c,-2.091105,3.0,22,c_22_3.0,0.387579,1.101376,0.947835,-2.093294
23,c,-2.846721,3.0,34,c_34_3.0,0.357333,1.015426,1.029087,-2.850781
24,c,-2.781488,3.0,103,c_103_3.0,0.293090,0.832866,1.227277,-2.785364
25,d,-2.644742,1.0,0,d_0_1.0,1.000000,2.841679,0.000000,-2.648245
26,d,-2.727439,1.0,18,d_18_1.0,0.491980,1.398049,0.709317,-2.731165
27,d,-3.775743,1.0,25,d_25_1.0,0.282476,0.802705,1.264163,-3.782889
28,d,-4.879311,1.0,31,d_31_1.0,0.204342,0.580675,1.587958,-4.891253
29,d,-7.265588,1.0,35,d_35_1.0,0.050757,0.144235,2.980709,-7.292111
30,d,-5.475932,1.0,40,d_40_1.0,0.103229,0.293343,2.270808,-5.490979
31,d,-3.381657,2.0,18,d_18_2.0,0.509981,1.449203,0.673381,-3.387388
32,d,-4.130674,2.0,25,d_25_2.0,0.274433,0.779849,1.293050,-4.139228
33,d,-4.217018,2.0,31,d_31_2.0,0.242643,0.689513,1.416164,-4.225934
34,d,-5.599666,2.0,40,d_40_2.0,0.121613,0.345585,2.106911,-5.615403
35,d,-3.270547,3.0,18,d_18_3.0,0.463638,1.317509,0.768652,-3.275907
36,d,-4.206029,3.0,25,d_25_3.0,0.408868,1.161871,0.894364,-4.214900
37,d,-4.297678,3.0,31,d_31_3.0,0.311584,0.885422,1.166086,-4.306940
38,d,-7.580787,3.0,35,d_35_3.0,0.067609,0.192123,2.694013,-7.609667
39,d,-5.319238,3.0,40,d_40_3.0,0.211236,0.600266,1.554777,-5.333435
40,d,-6.487941,3.0,51,d_51_3.0,0.061864,0.175798,2.782817,-6.509079

Now, we can export the master table, with the corrected data from both Cline assay (quantification) and EA-IRMS for each enzyme.

In [29]:
# Export master table with the data with all corrections

df_master.to_csv(f'{homedir}/ctep_wt/data/processed/EA_cline/20210330_EA_cline.csv')

# Calculate $\epsilon$

In [30]:
# Get the slope and intercept for each treatment

df_linreg = df_master.groupby(['treatment']).apply(
        lambda g: (((LinearRegression().fit((g.minus_ln_f_R.values).\
                                      reshape((-1,1)), g.d34S_sulfide.values)\
.coef_[0], LinearRegression().fit((g.minus_ln_f_R.values).reshape((-1,1)), \
                         g.d34S_sulfide.values).intercept_, LinearRegression().\
                     fit((g.minus_ln_f_R.values).reshape((-1,1)), g.d34S_sulfide.values).\
                     score((g.minus_ln_f_R.values).reshape((-1,1)), g.d34S_sulfide.values)\
                         )))).apply(pd.Series)\
.rename(columns={0:'slope', 1:'intercept', 2: 'R_squared'}).reset_index()

# Assign name as the index column
#df_100 =df_100.round(2)
df_linreg

   treatment     slope  intercept  R_squared
0  b_march22 -1.409537  -3.053725   0.942641
1          c -0.312208  -2.163652   0.128467
2          d -1.686628  -2.168766   0.914034

# Plot of the isotope data

In [31]:
# Group by treatment
df_group = df_master.groupby(['treatment'])

# Define colors
colors = sns.color_palette('colorblind', n_colors=len(df_group))
# Define markers
markers = ['.', 'o', 'd','*']

# Define fig and axes
fig = plt.figure(figsize=(2.95, 1.95), dpi=192)
ax = fig.add_subplot(111)

# Loop through replicates
for i, (group, data) in enumerate(df_group):
    #Calculate trendline  
    z = np.polyfit(data.minus_ln_f_R, data.d34S_sulfide, 1)
    p = np.poly1d(z)
 
    # Plot fit
    ax.plot(data.minus_ln_f_R, p(data.minus_ln_f_R), c=colors[i])
    
    # Plot experimental data
    ax.scatter(data.minus_ln_f_R, data.d34S_sulfide, color=colors[i], marker=markers[i],
              label = group)
    #ax.set_title('DddY')
    ax.set_xlabel('$-ln (f_R)$')
    ax.set_ylabel('ln ($\delta{}^{34}S_{VCDT}$+1) (‰)')
    #ax.set_ylim(14,19,1)

#Show legend
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

#Save figure
fig.savefig(f'{homedir}/ctep_wt/figures/ctepwt_fr_sulfide.pdf', bbox_inches='tight')

Notes:
-The control must be repeated and in triplicates, with newly autoclaved media. these values must be substituted as the 0 for one of the bs and d.
-Temporarily, a0 was relabelled as d0 and c0 for the EA measurements.